<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="author" content="熊滔"><meta name="description" content="人生天地间，忽如远行客"><link rel="alternative" href="/atom.xml" title="Coder" type="application/atom+xml"><link rel="icon" href="/favicon.png"><title>Java异常 - Coder</title>
<link rel="stylesheet" href="https://lastknightcoder.gitee.io/css/main.css">

<link rel="stylesheet" href="https://lastknightcoder.gitee.io/js/fancybox/jquery.fancybox.min.css">
<!--[if lt IE 9]><script>(function(a,b){a="abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video".split(" ");for(b=a.length-1;b>=0;b--)document.createElement(a[b])})()</script><![endif]-->
<script src="https://lastknightcoder.gitee.io/js/jquery-3.1.1.min.js"></script>

<script src="https://lastknightcoder.gitee.io/js/fancybox/jquery.fancybox.min.js"></script>
<meta name="generator" content="Hexo 4.2.0"></head><body style="opacity:0"><header class="head"><h1 class="head-title u-fl"><a href="https://lastknightcoder.gitee.io/">Coder</a></h1><nav class="head-nav u-fr"><ul class="head-nav__list"><li class="head-nav__item"><a class="head-nav__link" href="https://lastknightcoder.gitee.io/tags">标签</a></li><li class="head-nav__item"><a class="head-nav__link" href="https://lastknightcoder.gitee.io/archives">目录</a></li></ul></nav></header><main class="main"><article class="post"><header class="post__head"><time class="post__time" datetime="2019-08-04T16:00:00.000Z">2019-08-05 00:00:00</time><h1 class="post__title"><a href="https://lastknightcoder.gitee.io/Java%E5%BC%82%E5%B8%B8/">Java异常</a></h1><div class="post__main echo"><p>所谓的异常就是不正常，我们在之前很多地方有碰到异常，比如对象向下转型时有碰到ClassCastException。所有的异常都继承自Exception类。Exception下面有一个重要的的子类叫做RuntimeException。</p>
<p>异常分为编译期异常和运行时异常，如Exception就是编译期异常，而RuntimeException是运行时异常，如果在方法中抛出了一个编译期异常，那么必须处理该异常，继续向上抛出或者就地处理，而对于运行异常可以选择不处理，那么就会默认交给JVM处理。</p>
<h2 id="处理异常的过程"><a href="#处理异常的过程" class="headerlink" title="处理异常的过程"></a>处理异常的过程</h2><p>首先JVM检测到了异常，这时JVM会创建一个异常对象，该对象包含发生错误的内容、原因和位置。如果在发生异常处的方法内没有异常处理逻辑，那么JVM会把该异常抛给这个方法的调用者，如果该调用者也没有异常处理逻辑，那么就会一直向上抛出，直到遇到main方法，如果main方法也没有异常处理逻辑，那么这时异常就会抛给JVM，JVM会打印红色字体至控制台，并且终止Java程序的运行。</p>
<p>与异常有关的关键字有五个，分别为throw, throws, try, catch, finally。下面介绍这五个关键字的作用。</p>
<h2 id="throw"><a href="#throw" class="headerlink" title="throw"></a>throw</h2><p>throw关键字用于在方法中抛出一个异常，如下</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">double</span> <span class="title">divide</span><span class="params">(<span class="keyword">double</span> a, <span class="keyword">double</span> b)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">if</span> (b == <span class="number">0</span>) &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> ArithmeticException(<span class="string">"除0"</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> a/b;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>这个方法的作用是a/b，在检测到b=0时，我们抛出了一个异常，并给出提示信息”除0”。现在我们在main方法中调用该方法</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line">System.out.println(divide(<span class="number">5</span>,<span class="number">0</span>));</span><br></pre></td></tr></table></figure>

<p>由于我们没有对异常进行处理，所以程序会进行终结并在控制台打印出信息：</p>
<center>
     <img src="https://gitee.com/lastknightcoder/blogimage/raw/master/img/Java32.png"/>
</center>

<p><strong>注意：</strong></p>
<ul>
<li><code>throw</code>必须写在方法的内部</li>
<li><code>new</code>的必须是<code>Exception</code>或其子类</li>
</ul>
<h2 id="throws"><a href="#throws" class="headerlink" title="throws"></a>throws</h2><p>throws的作用是声明异常，或者说叫把异常抛给调用者，我们知道，编译期异常是必须要进行处理，那么处理的办法有两种，一种就是把继续向上抛出，另一种就是使用try-catch进行处理。而throws就是将异常继续抛出，现在我们将上面的ArithmeticException改为Exception，由于Exception为编译期异常，必须进行处理，否则编译不通过</p>
<center>
     <img src="https://gitee.com/lastknightcoder/blogimage/raw/master/img/Java33.png"/>
</center>


<p>由图片可以知道，由于我们没有对该异常处理，所以编译没有通过，我们这里的处理办法就是继续抛出</p>
<center>
     <img src="https://gitee.com/lastknightcoder/blogimage/raw/master/img/Java34.png"/>
</center>


<p>我们通过throws关键字抛出异常了，但是我们发现在main方法处又出现了问题，这是因为main方法没有处理divide()方法可能抛出的异常，因为divide()抛出的异常为编译期异常，必须进行处理，这里我们继续向上抛出，如下</p>
<center>
     <img src="https://gitee.com/lastknightcoder/blogimage/raw/master/img/Java35.png"/>
</center>


<p>这时代码就不会报错了。</p>
<p><strong>注意：</strong></p>
<ul>
<li>使用<code>throws</code>时可以抛出多个异常，异常与异常之间使用逗号隔开</li>
<li>如果抛出的多个异常具有父子类关系，那么抛出父类异常就可以了</li>
</ul>
<h2 id="try-catch"><a href="#try-catch" class="headerlink" title="try-catch"></a>try-catch</h2><p>虽然我们通过throws可以向上抛出异常，但是如果不进行处理的话，最终还是会抛出给JVM，而JVM的处理方法就是打印异常信息然后终止程序。我们应该在异常发生时进行捕获，这个时候就不会将异常最终抛给JVM，程序就不会终止，而是会继续的执行下去。进行捕获的代码就是try-catch。具体格式为</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">//可能发生异常的代码</span></span><br><span class="line">&#125; <span class="keyword">catch</span> &#123;接收异常的变量&#125; &#123;</span><br><span class="line">    <span class="comment">//对异常进行处理</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>所以我们重写上面的那个方法为</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">TestException</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            <span class="comment">//可能发生异常的代码</span></span><br><span class="line">            System.out.println(divide(<span class="number">5</span>,<span class="number">0</span>));</span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">            <span class="comment">//这里对异常的处理只是将异常打印出来</span></span><br><span class="line">            <span class="comment">//处理异常后并不会终止程序，所以后面的代码还是可以执行</span></span><br><span class="line">            System.out.println(e);</span><br><span class="line">        &#125;</span><br><span class="line">        </span><br><span class="line">        System.out.println(<span class="string">"后续代码"</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">double</span> <span class="title">divide</span><span class="params">(<span class="keyword">double</span> a, <span class="keyword">double</span> b)</span> </span>&#123;</span><br><span class="line">        </span><br><span class="line">        <span class="keyword">if</span> (b == <span class="number">0</span>) &#123;</span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> ArithmeticException(<span class="string">"除0"</span>); </span><br><span class="line">        &#125;</span><br><span class="line">        </span><br><span class="line">        <span class="keyword">return</span> a/b;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>运行结果为</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line">java.lang.ArithmeticException: 除<span class="number">0</span></span><br><span class="line">后续代码</span><br></pre></td></tr></table></figure>

<p>可见后面的代码执行了。</p>
<p>Throwable(它是Exception的父类)中有三个处理异常的方法</p>
<ul>
<li>getMessage<ul>
<li>打印简短信息</li>
</ul>
</li>
<li>toString<ul>
<li>就是上面的直接打印对象</li>
</ul>
</li>
<li>printStackTrace<ul>
<li>JVM向控制台输出的信息就是调用这个方法，该方法打印的信息很全</li>
</ul>
</li>
</ul>
<h2 id="finally"><a href="#finally" class="headerlink" title="finally"></a>finally</h2><p>其实在try-catch后面还可以跟一个finally块，我们知道如果没有发生异常的话，catch里面的代码块是不会执行的，而finally里的代码块，无论是是否抛出异常，都一定会执行的，所以finally里面的代码多用来释放资源的。我们来看一个例子</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    System.out.println(divide(<span class="number">5</span>,<span class="number">0</span>));</span><br><span class="line">&#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">    e.printStackTrace();</span><br><span class="line">&#125;<span class="keyword">finally</span> &#123;</span><br><span class="line">    System.out.println(<span class="string">"finally代码块"</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>这时是会抛出异常的，输出的结果为</p>
<center>
     <img src="https://gitee.com/lastknightcoder/blogimage/raw/master/img/Java36.png"/>
</center>


<p>可见finally里面的代码执行了，现在修改上面的代码为</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    System.out.println(divide(<span class="number">5</span>,<span class="number">1</span>));</span><br><span class="line">&#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">    e.printStackTrace();</span><br><span class="line">&#125;<span class="keyword">finally</span> &#123;</span><br><span class="line">    System.out.println(<span class="string">"finally代码块"</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>这时是不会抛出异常的，所以catch代码块里面的程序不会被执行，但是finally里面的代码始终会被执行，执行的结果为</p>
<center>
     <img src="https://gitee.com/lastknightcoder/blogimage/raw/master/img/Java37.png"/>
</center>


<p><strong>注意：</strong></p>
<ul>
<li>由于finally里面的代码一定是会执行的，所以要避免在finally里面写return语句，否则返回的一直是finally里面的结果。</li>
</ul>
<h2 id="多异常捕获"><a href="#多异常捕获" class="headerlink" title="多异常捕获"></a>多异常捕获</h2><h3 id="多次捕获，多次处理"><a href="#多次捕获，多次处理" class="headerlink" title="多次捕获，多次处理"></a>多次捕获，多次处理</h3><p>即使用多个try-catch语句块</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">//可能发生异常的代码</span></span><br><span class="line">&#125; <span class="keyword">catch</span>(异常<span class="number">1</span> e) &#123;</span><br><span class="line">    <span class="comment">//处理异常1</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">//可能发生异常的代码</span></span><br><span class="line">&#125; <span class="keyword">catch</span>(异常<span class="number">2</span> e) &#123;</span><br><span class="line">    <span class="comment">//处理异常2</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">...</span><br></pre></td></tr></table></figure>

<h3 id="一次捕获，多次处理"><a href="#一次捕获，多次处理" class="headerlink" title="一次捕获，多次处理"></a>一次捕获，多次处理</h3><p>即一个try匹配多个catch</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">//可能发生异常的代码</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (异常<span class="number">1</span> e) &#123;</span><br><span class="line">    <span class="comment">//处理异常1</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (异常<span class="number">2</span> e) &#123;</span><br><span class="line">    <span class="comment">//处理异常2</span></span><br><span class="line">&#125; ...</span><br></pre></td></tr></table></figure>

<p>如果在try中发生了异常，那么首先会判断这个异常能不能被异常1接收，如果能那么就在第一个catch中进行处理，如果不能，那么就判断能不能被异常2接收，以此类推。</p>
<p>这里需要注意的点是，父类异常必须子类异常后面。假设父类异常写在前面，如果发生了子类异常，根据多态，父类能够接收这个异常，所以写在后面的子类异常永远接受=收不到这个异常，就相当于是死代码了。</p>
<h3 id="一次捕获，一次处理"><a href="#一次捕获，一次处理" class="headerlink" title="一次捕获，一次处理"></a>一次捕获，一次处理</h3><p>就是在catch中使用Exception变量接收异常，因为所有的异常都是Exception的子类，所以可以接收所有的异常</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">//可能发生异常的代码</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">    <span class="comment">//处理异常</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="子类注意事项"><a href="#子类注意事项" class="headerlink" title="子类注意事项"></a>子类注意事项</h2><p>如果父类方法抛出多个异常，子类重写了该方法，那么子类方法有三种方案</p>
<ul>
<li>抛出相同异常</li>
<li>抛出父类异常的子类</li>
<li>不抛出异常</li>
</ul>
<p>如果父类的方法没有抛出异常，那么子类重写的方法也不能抛出异常。该子类产生的异常只能try-catch捕获处理，不能使用throws抛出。</p>
<h2 id="自定义异常"><a href="#自定义异常" class="headerlink" title="自定义异常"></a>自定义异常</h2><p>自定义的异常必须继承一个异常类。如果继承的是Exception，那么该异常就是编译期异常，如果继承的是RuntimeException，那么就是运行时异常。下面简单的演示</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">MyException</span> <span class="keyword">extends</span> <span class="title">RuntimeException</span></span>&#123;</span><br><span class="line">    <span class="comment">//一个空参构造方法</span></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="title">MyException</span><span class="params">()</span></span>&#123;&#125;</span><br><span class="line">    <span class="comment">//一个带异常信息的构造方法</span></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="title">MyException</span><span class="params">(String message)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">super</span>(message);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>现在进行测试</p>
<figure class="highlight java"><table><tr><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">TestMyException</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        divide(<span class="number">5</span>,<span class="number">0</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">double</span> <span class="title">divide</span><span class="params">(<span class="keyword">double</span> a, <span class="keyword">double</span> b)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">if</span> (b == <span class="number">0</span>) &#123;</span><br><span class="line">            <span class="comment">//继承至RuntimeException，是运行时异常，可以不进行处理</span></span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> MyException(<span class="string">"除0"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">return</span> a / b;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>结果为</p>
<center>
     <img src="https://gitee.com/lastknightcoder/blogimage/raw/master/img/Java38.png"/>
</center>


</div></header><footer class="post__foot u-cf"><ul class="post__tag u-fl"><li class="post__tag__item"><a class="post__tag__link" href="https://lastknightcoder.gitee.io/tags/Java/">Java</a></li><li class="post__tag__item"><a class="post__tag__link" href="https://lastknightcoder.gitee.io/tags/%E5%BC%82%E5%B8%B8/">异常</a></li></ul></footer></article><section class="reward"><a class="btn-reward" href="#">打赏</a><div class="reward-wrapper clearfix"><img src="https://lastknightcoder.gitee.io/img/wechatpay.png" title="微信"><img src="https://lastknightcoder.gitee.io/img/alipay.png" title="支付宝"></div></section></main><footer class="foot"><div class="foot-copy">&copy; 2019 - 2020 熊滔</div></footer>
<script src="https://lastknightcoder.gitee.io/js/scroller.js"></script>

<script src="https://lastknightcoder.gitee.io/js/main.js"></script>
</body></html>